--DROP SEQUENCE common.SEQ_CLIENT_ID;

CREATE SEQUENCE common.seq_client_id START WITH 1 NOMAXVALUE MINVALUE 1 NOCYCLE NOCACHE NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM seq_client_id FOR common.seq_client_id;