CREATE TABLE status_code_t
(
  ID                        NUMBER               NOT NULL,
  DESCRIPTION               VARCHAR2(100 BYTE)   NOT NULL,
  PLSQL_CONSTANT_NAME       VARCHAR2(30 BYTE),
  QEM_RECOMMENDATION        VARCHAR2(4000 BYTE),
  QEM_SUSTITUTE_STRING      VARCHAR2(4000 BYTE),
 CONSTRAINT XPK_STATUS_CODE_ID  
 PRIMARY KEY (ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;